// my-admin/src/views/setting/index.vue
<template>
  <div>
      <my-crumb-slot key="setting">
      <a-button size="mini" type="primary" @click="removeKeepalive('MemberList')">测试删除列表缓存</a-button>
    </my-crumb-slot>
    <a-layout class="list-wrap">
      <a-form :model="params">
        <a-form-item label="限制输入字母">
          <my-input v-model="params.name" :pattern="/^[a-zA-Z]{0,20}$/" />
        </a-form-item>
        <a-form-item label="限制输入金额">
          <my-input v-model="params.money" :pattern="/^(\d{1,10})?(\.([0-9]{0,2}))?$/" />
        </a-form-item>
        <a-form-item label="限制输入数字">
          <my-input v-model="params.number" :pattern="/^\d{1,20}$/" />
        </a-form-item>
        <a-form-item label="限制输入手机号">
          <my-input v-model="params.mobile" :pattern="/^1([3-9](\d{0,9})?)?$/" />
        </a-form-item>
        <a-form-item label="下拉框单选">
          <my-select v-model="params.type" :options="options" :formatter="({ id, name }) => [+id, name]" />
        </a-form-item>
        <a-form-item label="下拉框多选">
          <my-select v-model="params.types" :options="options" formatter="id,name" multiple @change="handleChange" />
        </a-form-item>
        <a-form-item label="日期区间">
          <my-date-range v-model:start="params.dateStart" v-model:end="params.dateEnd" />
        </a-form-item>
        <a-form-item label="地址选">
          <my-area-picker v-model="params.area" />
        </a-form-item>
        <a-form-item label="单选框">
          <my-radio v-model="params.radio" :options="options" formatter="id,name" />
        </a-form-item>
        <a-form-item label="复选框">
          <my-checkbox v-model="params.checkbox" :options="options" :formatter="({ id, name }) => [id, name]" />
        </a-form-item>
        <a-form-item label="开关">
          <my-tips error success>
            <my-switch v-model="params.switch" @change="useResolve" />
          </my-tips>
        </a-form-item>
        <a-form-item label="图片上传">
          <my-tips error position="right">
            <my-upload v-model="params.image" multiple :limit="3" :action="handleUpload" origin="https://static-nk.liux.co"
              style="width: unset" />
          </my-tips>
        </a-form-item>

      </a-form>
      <a-row style="padding-left: 50px;">
        <a-space wrap style="width: 600px;">
          <my-button @click="onJsonPost">json提交</my-button>
            <my-button @click="onFormPost">form提交</my-button>
          <a-button @click="$router.back()">返回</a-button>
          <my-button @click="useResolve">提交按钮</my-button>
          <my-tips success>
            <my-button @click="useResolve">tips提交按钮</my-button>
          </my-tips>
          <my-tips success error>
            <my-button type="primary" @click="useResolve">操作成功</my-button>
            <my-button type="primary" status="warning" @click="useReject">操作失败</my-button>
          </my-tips>
          <my-confirm status="danger" width="230px" title="你果真要删除它吗？" @confirm="useResolve">删除</my-confirm>
          <my-confirm type="primary" title="请选择审核状态">
            <template #default>
              <a-button type="primary">审核</a-button>
            </template>
            <template #cancel="attrs">
              <my-tips error success>
                <my-button @click="useReject" type="primary" status="warning">不通过</my-button>
              </my-tips>
            </template>
            <template #confirm="attrs">
              <my-tips error success>
                <my-button @click="useResolve" type="primary" status="success">通过</my-button>
              </my-tips>
            </template>
          </my-confirm>
          <my-tips error success>
            <!-- 子组件包含多个按钮时，同步所有子组件的状态 -->
            <my-download type="primary" @click="handleDownload">
              <template #icon><icon-download /></template>
              下载
            </my-download>
            <my-download type="outline" @click="handleExport({ abc: 123 })">
              <template #icon><icon-export /></template>
              导出
            </my-download>
            <my-upload :action="handleUpload">
              <template #upload-button="{ loading, disabled }">
                <a-button type="primary" :loading="loading" :disabled="disabled">
                  <template #icon><icon-upload /></template>
                  {{ loading ? '正在处理' : '点击上传' }}
                </a-button>
              </template>
            </my-upload>
          </my-tips>
        </a-space>
      </a-row>
    </a-layout>
  </div>

</template>
<script>
export default {
  name: 'BasicsComponents',
}
</script>
<script setup>
import { IconDownload, IconExport, IconUpload } from '@arco-design/web-vue/es/icon'
import { POST_SUCCESS, POST_ERROR, GET_DOWNLOAD, POST_UPLOAD , POST_CHANGE } from '@/http'
import { http } from '@/http'
import { reactive, watch, toRaw } from 'vue'
import { removeKeepalive } from '../../router/keepalive'

const params = reactive({
  name: 'Master',
  money: 999.999,
  number: 999,
  mobile: '18888888888',
  radio: '1',
  checkbox: '2',
  type: '2',
  switch: '',
  image: '',
  types: '1,2',
  // types :  [1,3] ,
})

setTimeout(() => {
  params.image = 'https://static-nk.liux.co/image8/13462fa/28194a0700023d15_400_400.jpg'
}, 1000)

watch(params, params => {
  console.log('params:', toRaw(params))
})

const options = [
  { id: 'aaa', name: 'aaa' },
  { id: '1', name: '选项一' },
  { id: 2, name: '选项二', disabled: true },
  { id: 3, name: '选项三' },
]

const useResolve = () => {
  return http.delete(POST_SUCCESS, { name: 'admin', password: 123456 })
  // return new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve({ message : '我去，居然成功了' })
  //   } , 1000)
  // })
}

const useReject = async () => {
  const res = await http({ url: POST_ERROR, params: { id: '999' } })
  console.log('useReject', res)
  return res
}

const handleChange = (v, e) => {
  console.log('handleChange', v, e)
}


const handleOk = close => {
  // setTimeout(close , 2000)
  return false
}

const handleDownload = () => {
  return http({ url: GET_DOWNLOAD, responseType: 'blob', intact: true })
}

const handleExport = params => {
  return http({ url: GET_DOWNLOAD, responseType: 'blob', params })
}

const handleUpload = (formData, config) => {
  return http.post(POST_UPLOAD, formData, config)
}

const onJsonPost=async ()=>{
  return http.post(POST_CHANGE, params,{type:'json'})
}

const onFormPost = async () => {
  return await http.post(POST_CHANGE, params)
}

</script>

<style scoped lang="less">
.list-wrap {
  padding: 20px;

  &>.a-row {
    margin-top: 20px;
  }

  :deep(.my-input),
  :deep(.my-select),
  :deep(.my-date-range),
  :deep(.arco-select-view) {
    width: 300px;
  }

  .my-button+.my-button {
    margin-left: 10px;
  }
}
</style>

// react-admin/src/view/setting/index.jsx
import { Descriptions } from 'antd'
import React, { useEffect, useState } from 'react'
import { MyButton, MyTips, MySwitch, MyInput, MyDateRange, MyRadio, MyCheckbox, MySelect, MyConfirm, MyUpload } from '../../components'
import { Button, Space, Tooltip, Menu, Form, Input, DatePicker, Radio, Checkbox, Select } from 'antd'
const { RangePicker } = DatePicker
import { http, POST_UPLOAD } from '../../http'

const Setting = () => {
    const useResolve = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('操作成功')
            }, 1500)
        })
    }

    const useReject = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                reject('操作失败')
            }, 1500)
        })
    }

    const useSwitch = val => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('操作成功')
            }, 1500)
        }).then(res => {
            setParams({ ...params, a: { switch: val } })
        })
    }

    const handleUpload = (formData, config) => {
        return http.post(POST_UPLOAD, formData, config)
    }


    const options = [
        { id: '1', name: '选项一' },
        { id: 2, name: '选项二', disabled: true },
        { id: 3, name: '选项三' },
    ]

    const getDetail = () => {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve({
                    input: '123',
                    start: '2024-01-01',
                    end: '2024-01-02',
                    a: {
                        switch: 1
                    },
                    radio: 1,
                    checkbox: ['1', 2],
                    select: ['1', 2],
                    image: 'https://static-nk.liux.co/image8/13462fa/28194a0700023d15_400_400.jpg'
                })
            })
        })
    }
    useEffect(() => {
        getDetail().then(res => {
            form.setFieldsValue(res);
            setParams(res)
        })
        console.log('useEffect');
    }, [])

    const [params, setParams] = useState({})
    const [form] = Form.useForm();

    const onFinish = (values) => {
        console.log(values);
    }
    return (
        <>
            <Descriptions title="测试封装的组件" column={1} className='outlet-main'>
                <div>
                    {JSON.stringify(params)}
                </div>

                <Descriptions.Item label="按钮">
                    <Space>
                        <MyButton type="primary" onClick={useResolve}>加载按钮</MyButton>
                        <MyTips success>
                            <MyButton type="primary" onClick={useResolve}>成功提示</MyButton>
                        </MyTips>
                        <MyTips error>
                            <MyButton type="primary" onClick={useReject}>错误提示</MyButton>
                        </MyTips>
                        <MyTips success error>
                            <div>
                                多个按钮同步状态：
                            </div>
                            <MyButton type="primary" onClick={useResolve}>成功提示</MyButton>
                            <MyButton danger type="primary" onClick={useReject}>错误提示</MyButton>
                        </MyTips>
                    </Space>
                </Descriptions.Item>
                <Descriptions.Item label="开关">
                    <MyTips success>
                        <MySwitch onChange={useSwitch} value={params.a?.switch} />
                    </MyTips>
                </Descriptions.Item>
                <Descriptions.Item label="输入框">
                    <Space>
                        数字输入框: <MyInput value={params.input} pattern={/^\d*$/} update={v => setParams({ ...params, input: v })} />
                        字母输入框: <MyInput value={params.input} pattern={/^[a-zA-Z]*$/} />
                        金额输入框: <MyInput value={params.input} pattern={/^(\d{1,10})?(\.([0-9]{0,2}))?$/} />
                        手机号码输入框: <MyInput value={params.input} pattern={/^1?([3-9](\d{0,9})?)?$/} />
                        普通输入框: <MyInput value={params.input} />
                    </Space>
                </Descriptions.Item>
                <Descriptions.Item label="日期范围">
                    <MyDateRange style={{width:'400px'}}  end={params.end} start={params.start} update={(start, end) => setParams({ ...params, start, end })} />
                </Descriptions.Item>
                <Descriptions.Item label="单选">
                    <MyRadio options={options} formatter="id,name" value={params.radio} update={radio => setParams({ ...params, radio })}>
                        <Radio value={4}>选项4</Radio>
                        <Radio value={5}>选项5</Radio>
                    </MyRadio>
                </Descriptions.Item>
                <Descriptions.Item label="复选">
                    <MyCheckbox options={options} formatter="id,name" value={params.checkbox} update={checkbox => setParams({ ...params, checkbox })}>
                        <Checkbox value={4}>选项4</Checkbox>
                    </MyCheckbox>
                </Descriptions.Item>
                <Descriptions.Item label="下拉">
                    <MySelect options={options} formatter="id,name" value={params.select} update={select => setParams({ ...params, select })}>
                        <Select.Option value="123" key="123">123</Select.Option>
                    </MySelect>
                </Descriptions.Item>
                <Descriptions.Item label="确定操作">
                    <MyConfirm title="确定要删除吗" onConfirm={useResolve} type="primary" danger>
                        删除
                    </MyConfirm>
                </Descriptions.Item>
                <Descriptions.Item label="表单">
                    <Form form={form} onFinish={onFinish}>
                        <Form.Item label="图片上传" name="image" rules={[{ required: true }]}>
                            <MyTips error success>
                                <MyUpload accept="image/jpeg" multiple action={handleUpload} origin="https://static-nk.liux.co" maxCount={3} />
                            </MyTips>
                        </Form.Item>
                        <MyTips success error>
                          <MyUpload action={handleUpload} BtnSlot={<Button type="primary">上传</Button>} />
                        </MyTips>
                        <Form.Item label="姓名" name="input" rules={[{ required: true }]}>
                            <MyInput pattern={/^\d*$/} ></MyInput>
                        </Form.Item>
                        <Form.Item label="开关" name={['a', 'switch']} rules={[{ required: true }]}>
                            <MySwitch></MySwitch>
                        </Form.Item>
                        <Form.Item label="日期" name="start" rules={[{ required: true }]}>
                            <MyDateRange form={form} endName="end" isForm />
                        </Form.Item>
                        <Form.Item label="单选" name="radio" rules={[{ required: true }]}>
                            <MyRadio options={options} formatter={({ id, name }) => [id, name]} value={1} >
                                <Radio value={4}>选项4</Radio>
                                <Radio value={5}>选项5</Radio>
                            </MyRadio>
                        </Form.Item>
                        <Form.Item label="多选" name="checkbox" rules={[{ required: true }]}>
                            <MyCheckbox options={options} formatter="id,name" value={params.checkbox} update={checkbox => setParams({ ...params, checkbox })}>
                                <Checkbox value={4}>选项4</Checkbox>
                            </MyCheckbox>
                        </Form.Item>
                        <Form.Item label="下拉" name="select">
                            <MySelect options={options} formatter="id,name" mode="multiple">
                                <Select.Option value="123" key="123">123</Select.Option>
                            </MySelect>
                        </Form.Item>
                        <MyButton type="primary" htmlType="submit">提交</MyButton>
                    </Form>
                </Descriptions.Item>
            </Descriptions>
        </>

    )
}

export default Setting
