// my-components/src/MyTable/MyTable.vue
<script lang="jsx">
import MyPagination from './MyPagination'
import { Row as ARow, Table as ATable, Button as Abutton, Space as Aspace } from '@arco-design/web-vue'
import { ref, watch, reactive, onMounted, computed, toRaw } from 'vue'
import { reduceProps, empty, typeOf } from '@wzh-/utils'
import router from '@/router'

/**
 * 表格组件
 * props.onRequest 数据源
 * props.columns 列表配置
 * props.selections? 复选框
 * props.history? 值为真时，利用 url 记录当前查询的条件和分页（暂时只支持哈希路由）
 * props.load? 值为真时组件载入后发送请求
 * props.bordered? 是否显示边框（默认否）
 * props.rowSelection? 表格的行选择器配置
 * slots.params? 参数插槽，提供参数：{ params , search }
 * slots.pagination? 自定义分页区插槽，提供参数：{ dataInfo , search }
 */
export default {
    name: 'MyTable',
    emits: ['update:loading', 'change', 'update:selections', 'update:history'],
    props: {
        onRequest: { type: Function, require: true },//数据源
        selections: [Boolean, Array], // 复选框
        columns: { type: Array, required: true },
        load: { type: Boolean, default: true }, // 值为真时加载完组件马上获取数据
        rowKey: { default: 'id' }, // 预设 key = id
        history: Boolean, // 值为真时路由会记录
        bordered: { type: [Boolean, Object], default: false },
        rowSelection: { type: Object, default: () => ({}) },
    },
    // expose相当于defineExpose
    setup(props, { attrs, slots, emit, expose }) {
        const loading = ref(false)//表格loading

        const useLoading = () => {
            loading.value = true
            return () => loading.value = false
        }

        // 将 loading 同步到父组件
        watch(loading, bool => emit('update:loading', bool))

        // 进入页面,获取url中的参数
        // location.hash => #/member 获取#之后的值 decodeURIComponent  特殊字符=>原始字符
        const query = /\?(.+)$/.exec(location.hash)?.[1].split('&').reduce((_, str) => {
            const vs = str.split('=')
            const key = vs[0], value = vs[1]
            if (empty(vs) || empty(value)) {
                return _
            }
            return { ..._, [key]: decodeURIComponent(value) }
        }, {})

        // 查询条件
        const params = reactive({})
        // history时将url的除了分页的参数合并到params
        if (props.history) {
            Object.assign(params, reduceProps(query, ({ name }) => ['pageNo', 'pageSize'].includes(name)))
        }

        // 保存查询时使用的参数
        const paramsHistory = ref({})

        // props.history = true 时，通过 url 记录当前参数
        watch(paramsHistory, value => {
            if (!props.history) {
                return
            }
            const query = reduceProps(value, ({ value }) => empty(value))//删减空参数
            if (value?.pageNo === 1) delete query.pageNo // 删减非必要参数
            if (value?.pageSize === 10) delete query.pageSize // 删减非必要参数
            const { name } = router.currentRoute.value
            router.replace({ name, query })
            emit('update:history', query)
        })

        // 接口返回数据 包含分页参数
        const dataInfo = reactive({})

        watch(dataInfo, value => emit('change', value, params))

        // 列表数据
        const dataList = computed(() => dataInfo.results || [])

        //勾选的数据的rowkey数组 items=>item[rowKey] 用于回显表格的勾选
        const selectedKeys = computed(() => {
            const { selections, rowKey } = props
            return selections?.map?.(item => item[rowKey])
        })

        // 复选框变更时返回选中的数据对象 concat保证了不会丢失不是当前页的选项
        const doSelectedKeysChange = keyItems => {
            const { selections, rowKey } = props
            const selectedRows = keyItems.map(key => toRaw(selections.concat(dataList.value).find(item => item[rowKey] === key)))
            emit('update:selections', selectedRows)
        }

        const searchErr = ref(false)

        //查询
        const search = async _params => {
            searchErr.value = false
            //重置时清空查询条件
            if (_params === null) {
                // 不能直接赋值 reactive会丢失响应性
                reduceProps(params, ({ key }) => delete params[key])
            }
            // 非正常参数
            if (!typeOf(_params, 'object')) {
                _params = {}
            }
            //记录参数
            paramsHistory.value = { ...params, ..._params }
            const res = await props.onRequest(paramsHistory.value).catch(err => searchErr.value = true).finally(useLoading())
            Object.assign(dataInfo, res)
        }

        // 刷新数据
        const reload = () => {
            const pageNo = dataInfo.pageNo //当前页码
            const pageSize = dataInfo.pageSize //当前每页展示的数据条数
            return search({ pageNo, pageSize })
        }

        //导出方法
        expose({ search, reload })

        // 挂载后执行搜索
        onMounted(() => props.load && search())


        return () => {

            const { rowKey, selections, columns, bordered } = props

            // 重写render 将reload(刷新数据)注入render
            columns.map(item => {
                const fn = item.render
                if (!empty(fn)) {
                    item.render = rowInfo => fn(rowInfo, { reload })
                }
            })

            const slotErr = () => [
                <ARow class="empty-wrap" justify="center" align="center">
                    <Aspace>
                        <div>请求错误</div>
                        <Abutton type='text' onClick={search}>重试</Abutton>
                    </Aspace>
                </ARow>
            ]

            //预设插槽
            const {
                empty: slotEmpty = () => [
                    <ARow class="empty-wrap" justify="center" align="center">{loading.value ? '加载中...' : '暂无数据'}</ARow>
                ],
                // 查询条件
                params: slotParams = () => [],
                // 分页组件
                pagination: slotPagination = () => {
                    if (empty(dataInfo)) {
                        return []
                    }
                    const paginationAttrs = { disabled: loading.value, data: dataInfo, onChange: search }
                    return [<MyPagination {...paginationAttrs} />]

                },
            } = slots

            const tableAttrs = {
                class: 'my-table',
                scroll: { x: '100%', y: '100%' },
                pagination: false,
                data: dataList.value,
                rowKey,
                loading: loading.value,
                columns,
                bordered,
                ...attrs,
            }

            // 当配置了 selections 时，添加复选框关联配置
            if (typeOf(selections, 'array')) {
                const { rowSelection } = props
                const selectAttrs = {
                    rowSelection: {
                        width: 60,
                        type: 'checkbox',
                        showCheckedAll: true,
                        ...rowSelection
                    },
                    selectedKeys: selectedKeys.value,
                    'onUpdate:selectedKeys': doSelectedKeysChange
                }
                Object.assign(tableAttrs, selectAttrs)
            }

            const tableSlots = {
                ...slots,
                empty: () => searchErr.value ? slotErr() : slotEmpty({ loading: loading.value })
            }
            const Table = <ATable {...tableAttrs} v-slots={tableSlots} />

            return [
                ...slotParams({ params, search, loading: loading.value }),
                Table,
                ...slotPagination(dataInfo)
            ]
        }
    }
}

</script>
<style scoped lang="less">
.my-table {
    flex: 1;
    overflow: hidden;

    :deep(.arco-table-container) {
        height: 100%;

        .arco-scrollbar-type-embed:last-child {
            flex: 1;

            .arco-table-tr-empty>td {
                border: unset;

                .empty-wrap {
                    position: absolute;
                    top: 0;
                    right: 0;
                    bottom: 0;
                    left: 0;
                    color: #888;
                }
            }
        }
    }

    &+.my-pagination {
        margin: 20px auto 0;
    }
}
</style>

// react-components/src/MyTable/MyTable.jsx
import { Form, Table, Row, Button, Space } from 'antd'
import { useSearchParams } from 'react-router-dom'
import React, { useState, useMemo, useEffect, useImperativeHandle, useCallback, useRef, Children } from 'react'
import { empty, reduceProps, typeOf } from '@wzh-/utils'
import { useDeleteProps } from '../_hook'
import MyPagination from './MyPagination.jsx'
/**
 * 表格组件
 * onRequest 请求数据源
 * columns 列表配置 render注入reload方法
 * selections? 复选框[Boolean, Array]
 * history? 值为真时，利用 url 记录当前查询的条件和分页
 * load? 值为真时组件载入后发送请求
 * bordered? 是否显示边框（默认否）
 * rowSelection? 表格的行选择器配置 selections传入数组预设复选的操作通过updateSelections更新selections
 * searchSlot? 参数插槽，提供参数：{ search,form }
 * pagination? 自定义分页区插槽，提供参数：{ dataInfo , search }
 * historySelect是否支持跨页勾选
 */
const MyTable = (props, ref) => {

    const {
        onRequest,
        rowKey = "id",
        columns,
        selections,
        updateSelections,
        history,
        load = true,
        rowSelection = {},//表格行是否可选择
        searchSlot,
        historySelect,
        bordered=false
    } = props

    const [loading, setLoading] = useState(false)
    const useLoading = () => {
        setLoading(true)
        return () => setLoading(false)
    }

    const [searchParams, setSearchParams] = useSearchParams()

    const [form] = Form.useForm()

    let query
    useEffect(() => {
        if (history) {
            // fromEntries 键值对数组转为对象
            // [['a', 1], ['b', 2], ['c', 3]]=>{ a: 1, b: 2, c: 3 }
            query = Object.fromEntries([...searchParams]);
            form.setFieldsValue(useDeleteProps(query, ['pageSize', 'pageNo']))
        }
    }, [])

    const [dataInfo, setDataInfo] = useState({})

    const dataSource = useMemo(() => dataInfo?.results || [], [dataInfo])

    const [error, setError] = useState(false)

    const ErrSlot = () => {
        return <Space style={{ height: "100%", justifyContent: "center" }}>
            {error.message}
            <Button onClick={reload}>刷新</Button>
        </Space>

    }

    //查询
    const search = async params => {
        // 重置
        if (params === null) {
            form.resetFields()
            setSearchParams({}, { replace: true })
        }
        // 非正常参数
        if (!typeOf(params, 'object') || params.nativeEvent) {
            params = {}
        }
        const formParams = form.getFieldsValue()
        const _params = reduceProps({ ...query, ...formParams, ...params }, ({ key, value }) => empty(value))
        if(history){
            // 记录参数 不增加路由记录
            setSearchParams(_params, { replace: true })
        }
        setError(false)
        const res = await onRequest(_params).catch(err => { setError(err) }).finally(useLoading())
        setDataInfo(res)
    }

    // 刷新数据
    const reload = () => {
        const pageNo = dataInfo?.pageNo || 1 //当前页码
        const pageSize = dataInfo?.pageSize || 10 //当前每页展示的数据条数
        return search({ pageNo, pageSize })
    }

    useEffect(() => {
        load && search()
    }, [])

    // render注入reload
    const _columns = useMemo(() => {
        return columns.map(item => {
            if (item.render) {
                const fn = item.render
                item.render = (text, record, index) => fn({ text, record, index }, { reload })
            }
        })
    }, [columns])

    const _props = {
        className: "my-table",
        dataSource,
        pagination: false,
        loading,
        scroll: { y: 240, x: "100%" },
        rowKey,
        columns: _columns,
        bordered,
        ...props,
    }

    const selectedRowKeys = useMemo(() => {
        return selections?.map?.(item => item?.[rowKey])
    }, [selections])

    if (typeOf(selections, 'array')) {
        const onSelect = (record, selected, selectedRows, nativeEvent) => {
            if (!updateSelections) {
                return
            }
            // 跨页多选
            if (historySelect) {
                let newSelections = []
                if (selected) {
                    newSelections = selections.concat(record)
                } else {
                    newSelections = selections.filter(item => item[rowKey] !== record[rowKey])
                }
                updateSelections(newSelections)

            } else {
                updateSelections(selectedRows.filter(Boolean))
            }

        }

        const onSelectAll = (selected, selectedRows, changeRows) => {
            if (!updateSelections) {
                return
            }
            // 跨页多选
            if (historySelect) {
                let newSelections = []
                if (selected) {
                    newSelections = selections.concat(changeRows)
                } else {
                    newSelections = selections.filter(item => !changeRows.includes(item))
                }
                updateSelections(newSelections)
            } else {
                updateSelections(selectedRows.filter(Boolean))
            }
        }

        const _selectProps = {
            rowSelection: {
                type: "checkbox",
                selectedRowKeys,
                onSelect,
                onSelectAll,
                ...rowSelection
            }
        }
        Object.assign(_props, _selectProps)
    }

    useImperativeHandle(ref, () => ({
        search,
        reload,
        dataInfo
    }))

    const formProps = {
        form,
        layout: "inline",
        labelAlign: "right",
        wrapperCol: { flex: 1 },
        labelCol: { flex: '80px' },
        variant: "filled",
        children: searchSlot({ search, form ,loading})
    }

    const paginationProps = {
        data: dataInfo || {},
        search,
        disabled: loading
    }

    return <>
        <Form {...formProps} />
        {error ? <ErrSlot /> : <Table {..._props} ></Table>}
        <MyPagination {...paginationProps} />
    </>;
}

export default React.forwardRef(MyTable);
