// my-components/src/MyTips/MyTips.vue
<script lang="jsx">
import { mergeProps, reactive, watch } from 'vue'
import { empty, typeOf, debug } from '@my-wzh/utils'

/**
 * 通用操作提示
 * 配合子组件的 onError 、 onSuccess 事件提示信息
 */

export default {
    name: 'MyTips',
    emits: ['update:disabled', 'update:visible'],//更新父组件disabled和visible值
    inheritAttrs: false,
    props: {
        delay: { type: Number, default: 1500 }, // 信息窗停留时间
        success: [Boolean, String], // 开/关 成功提示 (字符串时替换提示信息)
        error: [Boolean, String], // 开/关 错误提示 (字符串时替换提示信息)
    },
    setup(props, { attrs, slots, emit }) {
        const state = reactive({
            disabled: false,
            visible: false,
            message: '', // 提示信息
            backgroundColor: '', // 提示窗口的背景色
        })

        // 同步状态(标识当前按钮为凶手，其他)
        watch(() => state.disabled, bool => {
            emit('update:disabled', bool)
        })

        // 提示框显示的时候禁用按钮
        watch(() => state.visible, bool => {
            state.disabled = bool
        })

        // 子组件同步父组件
        const syncDisabled = bool => {
            state.disabled = bool
        }

        const setVisible = (bool, info) => {
            state.visible = bool
            emit('update:visible', bool, info)
        }

        // 提示信息
        const showTips = info => {
            debug('MyTips.showTips', info)
            state.message = info.message
            state.backgroundColor = typeOf(info, 'error') ? '#F7676F' : '#25C550'
            return new Promise(resolve => {
                setTimeout(() => setVisible(true, info)) // setTimeout 规避提示框错位
                setTimeout(() => resolve(setVisible(false, info)), props.delay)
            })
        }

        // 处理成功提示
        const onSuccess = async res => {
            const { success } = props
            if (success === false) {
                return setVisible(false, res)
            }
            let message = res?.message || '操作成功'
            if (typeOf(success, 'string')) {
                message = success
            }
            await showTips({ message })
        }

        // 处理错误提示
        const onError = async res => {
            const { error } = props
            if (error === false) {
                return setVisible(false, res)
            }
            let message = res.message || '操作失败'
            if (typeOf(error, 'string')) {
                message = error
            }
            await showTips(new Error(message))
        }

        return () => {

            const { visible, disabled, backgroundColor } = state
            // 获取插槽中的子组件
            let items = slots.default?.()

            // 空插槽
            if (empty(items)) {
                return []
            }
            // 多个子组件
            if (items.length > 1) {
                const children = items.map(item => {
                    const _attrs = { inheritDisabled: disabled, 'onUpdate:disabled': syncDisabled, ...props, ...attrs }
                    const _slots = { default: () => item }
                    return <MyTips {..._attrs} v-slots={_slots} />
                })
                return <a-space>{children}</a-space>
            }
            // my-tips
            const _attrs = {
                popperClass: 'my-tips',
                popupVisible: visible,
                updateAtScroll: true,
                backgroundColor,
                ...attrs,
            }
            const _slots = {
                // 泡泡弹窗提内容
                content: () => state.message,
                // 子组件
                default: () => {
                    const btn = items.find(({ props }) => !empty(props))
                    if (empty(btn)) {
                        return items
                    }
                    const props = {
                        ...btn.props,
                        'onUpdate:loading': syncDisabled,
                        disabled: disabled || attrs.inheritDisabled || btn.props.disabled,
                        onSuccess,
                        onError,
                    }
                    // 将 tips 状态变化嵌入 子组件
                    return Object.assign(btn, { props })
                },
            }
            return <a-tooltip {..._attrs} v-slots={_slots} />
        }
    }
}
</script>

// react-components/src/MyTips/MyTips.jsx
import { empty, typeOf } from '@wzh-/utils';
import { Tooltip, Space } from 'antd';
import React, { useState, useEffect } from 'react';
/**
 * 通用操作提示
 * 配合子组件的 onError 、 onSuccess 事件提示信息
 * delay弹窗延时 success,error是否显示弹窗 传入string时为弹窗的提示内容
 * btnDisabled 多个按钮共同的disabled
 * updateDisabled 更新按钮disabled
 * @param { delay, success, error} props
 * @returns
 */
const MyTips = (props) => {
    const { children, delay, success, error, updateDisabled, btnDisabled } = props

    // 提示窗口的背景色
    const [color, setColor] = useState('')

    // 提示内容
    const [title, setTitle] = useState()

    const [disabled, setDisabled] = useState(false)

    const syncDisabled=bool=>{
        setDisabled(bool)
    }

    // 是否显示气泡
    const [open, setOpen] = useState(false)

    useEffect(()=>{
        updateDisabled(open)
    },[open])

    const showTips = info => {
        const { message } = info

        setTitle(message)

        typeOf(info, 'error') ? setColor('#F7676F') : setColor('#25C550')

        return new Promise(resolve => {
            setTimeout(() => setOpen(true), 1)//防止按钮loading导致弹窗错位
            setTimeout(() => { setOpen(false); resolve(info) }, delay + 1)
        })
    }

    const onSuccess = async res => {
        if (success === false) {
            return
        }
        let message = res?.message || '操作成功'
        if (typeOf(success, 'string')) {
            message = success
        }
        showTips({ message })
    }

    const onError = (err) => {
        if (error === false) {
            return
        }
        let message = err?.message || '操作失败'
        if (typeOf(error, 'string')) {
            message = error
        }
        showTips(new Error(message))
    }


    if (!children) {
        return []
    }

    //多个插槽
    if (children.length > 1) {

        const tipsProps = {
            ...props,
            btnDisabled: disabled,
            updateDisabled: syncDisabled
        }

        const Items = children.map((item, key) => {
            if (typeOf(item.type, 'function')) {
                return <MyTips {...tipsProps} key={key}>{item}</MyTips>
            } else {
                return <MyTips key={key}>{item}</MyTips>
            }
        })

        return <Space>
            {Items}
        </Space>
    }

    // 单个插槽
    let _children = children//普通标签

    // 自定义组件
    if (typeOf(children.type,'function')) {
        //给子组件注入额外的props 为什么updateDisabled不能是syncDisabled syncDisabled是每个子节点自身的处理disabled的函数
        // updateDisabled来源于最外层的my-tips处理的是同一个disabled
        _children = React.cloneElement(children, { onSuccess, onError, disabled: btnDisabled, updateDisabled })
    }


    const _props = {
        ...props,
        overlayClassName: 'my-tips',
        open,
        color,
        title,
    }

    return <Tooltip {..._props} >
        {_children}
    </Tooltip>

}

MyTips.defaultProps = {
    delay: 1500, // 信息窗停留时间
    success: false, // 开/关 成功提示 (字符串时替换提示信息)
    error: false,//开/关 错误提示 (字符串时替换提示信息)
    updateDisabled:()=>{}
}

export default MyTips;
