// my-components/src/MyCrumb/MyCrumb.vue
<script lang="jsx">
import { computed } from 'vue'
import router from '@/router'


/**
 * 面包屑
 */
export default {
    name: "LayoutCrumb",
    props: {
        slots: { required: true },
        actionSlots: { required: true },
    },
    setup(props, { attrs }) {

        const route = router.currentRoute.value

        // 面包屑数据
        const matchedItems = computed(() => {
            const { meta, params, matched } = route
            const routes = matched.filter(({ meta }) => meta?.title)
            // params.matched 和 meta.matched 可对面包屑的数据进行二次改造
            return params.matched?.(routes) || meta.matched?.(routes) || routes
        })

        // 右侧插槽
        const actions = computed(() => {
            const { slots, actionSlots } = props
            const items = actionSlots[route.name] || []
            return items.concat(slots.default?.())
        })

        return () => {

            const items = matchedItems.value
            const len = items.length

            // 面包屑
            const breadcrumbItems = items.map((route, index) => {
                const { title } = route.meta

                if (len > index + 1) {
                    return [
                        <a-breadcrumb-item key={index}>
                            <router-link class="menu-link" to={route}>{title}</router-link>
                        </a-breadcrumb-item>
                    ]
                }
                return <a-breadcrumb-item>{title}</a-breadcrumb-item>
            })

            return [
                <a-row class="my-crumb" justify="space-between" align="center">
                    <a-row>
                        <a-breadcrumb {...attrs}>{breadcrumbItems}</a-breadcrumb>
                    </a-row>
                    <a-row class="action-wrap" justify="end" align="center">{actions.value}</a-row>
                </a-row>
            ]
        }
    }
}
</script>

<style scoped lang="less">
.my-crumb {
    flex-shrink: 0;
    height: 50px;
    padding: 0 20px;
    border-bottom: solid 1px #eee;

    .action-wrap {
        flex: 1;

        > :deep(*+*) {
            margin-left: 10px;
        }
    }

    .menu-link {
        background-color: inherit;

        &:hover {
            text-decoration: underline;
        }
    }
}
</style>

// react-components/src/MyCrumb/MyCrumb.jsx
import { Row, Breadcrumb, Space } from 'antd'
import routes from '@/router'
import { matchRoutes, useLocation, Link } from 'react-router-dom';

const style = { height: '50px', padding: "0 20px", borderBottom: 'solid 1px #eee' }


const MyCrumb = (props) => {
    const { children: slots } = props

    const { pathname } = useLocation()
    const matched = matchRoutes(routes, pathname)

    const itemRender = (item, params, items, paths) => {
        const { pathname, route } = item

        const last = items.indexOf(item) === items.length - 1;

        if (last) {
            return <span>{route?.meta?.title}</span>
        }
        return <Link to={route.redirect || pathname}>{route?.meta?.title}</Link>
    }


    return <Row justify="space-between" align="middle" style={style}>
        <Breadcrumb itemRender={itemRender} items={matched}></Breadcrumb>
        <Space>
            {slots}
        </Space>
    </Row>
}

export default MyCrumb;
