// react-admin/src/view/member/index.jsx
import { Form, Input, Button, Layout, Space, Col } from 'antd'
import { MyDateRange, MyTable } from '../../components'
import { http, GET_PAGE } from '../../http'
import { columns } from './columns'
import { useRef, useState } from 'react'

const Member = () => {

    const requestApi = async params => {
        const rs = await http.get(GET_PAGE, { pageSize: 20, ...params })
        return rs
    }

    const [selections, setSelections] = useState([
        {
            id: '61017nkp10qonjlvvl',
            name: '测试aji7ss357jg62b81',
            createTime: '2018-4-01 39:31:03',
            status: 1,
            picture: 'https://static-nk.liux.co/image8/13462fa/28194a0700023d15_400_400.jpg'
        }
    ])

    const searchSlot = ({ search, form, loading }) => {
        return <>
            <Col span={6}>
                <Form.Item name="name" label="名称">
                    <Input />
                </Form.Item>
            </Col>
            <Col span={6}>
                <Form.Item name="name2" label="名称2">
                    <Input />
                </Form.Item>
            </Col>

            <Col span={6}>
                <Form.Item name="name3" label="名称3">
                    <Input />
                </Form.Item>
            </Col>
            <Col span={6}>
                <Form.Item name="start" label="创建时间">
                    <MyDateRange form={form} isForm endName="end" />
                </Form.Item>
            </Col>
            <Col span={6}>
                <Form.Item name="name3" label="名称3">
                    <Input />
                </Form.Item>
            </Col>
            <Form.Item>
                <Space>
                    <Button type="primary" onClick={search} loading={loading}>查询</Button>
                    <Button onClick={() => search(null)} loading={loading}>重置</Button>
                    <Button onClick={() => search(null)}>新增</Button>
                </Space>
            </Form.Item>
        </>
    }

    const tableRef = useRef(null)

    return <Layout className='outlet-main'>
        以选择{selections.length}项
        <MyTable
            selections={selections}
            updateSelections={setSelections}
            bordered
            onRequest={requestApi}
            searchSlot={searchSlot}
            historySelect
            columns={columns}
            ref={tableRef}
            history
        />
    </Layout>
}

export default Member;

// my-admin/src/views/member/index.vue
<template>
  <my-crumb-slot key="member">
    <a-button>重制</a-button>
    <a-button>更新</a-button>
    <my-button>搜索</my-button>
  </my-crumb-slot>
  <my-table history @request="requestApi" :columns="columns" v-model:loading="loading" @change="change"  v-model:selections="selections">
    <template #params="{ params, search }">
      <a-form :model="params" layout="inline" auto-label-width>
        <a-form-item label="名称">
          <a-input v-model="params.name"></a-input>
        </a-form-item>
        <a-form-item label="名称">
          <a-input v-model="params.name"></a-input>
        </a-form-item>
        <a-space align="start">
          <a-button @click="search" type="primary" :loading="loading">查询</a-button>
          <a-button @click="search(null)" :loading="loading" type="outline">重置</a-button>
        </a-space>
      </a-form>
    </template>
  </my-table>
</template>
<script>
export default {
  name: 'MemberList'
}
</script>
<script setup>
import { ref, computed } from 'vue'
import { http, GET_OPTIONS, GET_PAGE } from '@/http';
import { columns } from './columns'

const requestApi = async params => {
  const rs = await http.get(GET_PAGE, params)
  console.log(rs)
  return rs
}

const loading=ref(false)

const change=(value,params)=>{
  console.log(value, params);
}

const selections=ref([{
  "id": "aji7ss357jg62b81",
  "name": "测试aji7ss357jg62b81",
  "createTime": "2018-4-01 39:31:03",
  "status": 1,
  "picture": "https://static-nk.liux.co/image8/13462fa/28194a0700023d15_400_400.jpg"
}])

</script>
<style scoped lang='less'></style>
