// my-admin/src/views/home.vue
<template>
  <a-row justify="center" align="center">
    <!-- <router-link :to="{ name: 'Member' }"> -->
      <a-image src="logo.png" width="100" :preview="false" />
    <!-- </router-link> -->
  </a-row>
</template>

<script setup>


</script>

<style scoped lang="less">
.arco-row {
  height: 100vh;
}
</style>

// react-admin/src/view/home.jsx
import { Row, Image } from 'antd'
import { useNavigate } from 'react-router-dom'


const Home = () => {
    const nav = useNavigate()
    return <>
        <Row align="middle" justify="center" style={{ height: '100%' }}>
            <Image onClick={() => nav('/member')} width="100px" src="logo.png" preview={false} />✨🍍
        </Row>
    </>
}

export default Home;
